// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu6SFstRM9_7YohOrKuFwEebeRHu2vPKk',
    appId: '1:678290610580:web:be7be1096678de09935781',
    messagingSenderId: '678290610580',
    projectId: 'yardify-a22ca',
    authDomain: 'yardify-a22ca.firebaseapp.com',
    databaseURL: 'https://yardify-a22ca-default-rtdb.firebaseio.com',
    storageBucket: 'yardify-a22ca.firebasestorage.app',
    measurementId: 'G-S02C0G3Z7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiWBSz7ozaUXfVPcb00v84hKC03CJHMWA',
    appId: '1:678290610580:android:51c07a19b624f555935781',
    messagingSenderId: '678290610580',
    projectId: 'yardify-a22ca',
    databaseURL: 'https://yardify-a22ca-default-rtdb.firebaseio.com',
    storageBucket: 'yardify-a22ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD15--3znrkhDOgCzwC8lBXJylixx1ecEc',
    appId: '1:678290610580:ios:16e32f7994fb0e8f935781',
    messagingSenderId: '678290610580',
    projectId: 'yardify-a22ca',
    databaseURL: 'https://yardify-a22ca-default-rtdb.firebaseio.com',
    storageBucket: 'yardify-a22ca.firebasestorage.app',
    iosBundleId: 'com.example.yardify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD15--3znrkhDOgCzwC8lBXJylixx1ecEc',
    appId: '1:678290610580:ios:16e32f7994fb0e8f935781',
    messagingSenderId: '678290610580',
    projectId: 'yardify-a22ca',
    databaseURL: 'https://yardify-a22ca-default-rtdb.firebaseio.com',
    storageBucket: 'yardify-a22ca.firebasestorage.app',
    iosBundleId: 'com.example.yardify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu6SFstRM9_7YohOrKuFwEebeRHu2vPKk',
    appId: '1:678290610580:web:4b00cfc98ea5d7f9935781',
    messagingSenderId: '678290610580',
    projectId: 'yardify-a22ca',
    authDomain: 'yardify-a22ca.firebaseapp.com',
    databaseURL: 'https://yardify-a22ca-default-rtdb.firebaseio.com',
    storageBucket: 'yardify-a22ca.firebasestorage.app',
    measurementId: 'G-XP8HZR47C6',
  );
}
